#
# OpenAPI Petstore
# This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSPetstore' -name 'PetApi' {
    Context 'Add-Pet' {
        It 'Test Add-Pet' {
            #$TestResult = Invoke-PetApiGetPetById -Body "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-DeletePet' {
        It 'Test Invoke-DeletePet' {
            #$TestResult = Invoke-PetApiGetPetById -PetId "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Find-PetsByStatus' {
        It 'Test Find-PetsByStatus' {
            #$TestResult = Invoke-PetApiGetPetById -Status "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Find-PetsByTags' {
        It 'Test Find-PetsByTags' {
            #$TestResult = Invoke-PetApiGetPetById -Tags "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-PetById' {
        It 'Test Get-PetById' {
            #$TestResult = Invoke-PetApiGetPetById -PetId "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Update-Pet' {
        It 'Test Update-Pet' {
            #$TestResult = Invoke-PetApiGetPetById -Body "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Update-PetWithForm' {
        It 'Test Update-PetWithForm' {
            #$TestResult = Invoke-PetApiGetPetById -PetId "TEST_VALUE" -Name "TEST_VALUE" -Status "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-UploadFile' {
        It 'Test Invoke-UploadFile' {
            #$TestResult = Invoke-PetApiGetPetById -PetId "TEST_VALUE" -AdditionalMetadata "TEST_VALUE" -File "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

}
