#
# OpenAPI Petstore
# This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'InlineObject' {
    Context 'InlineObject' {
        It 'Initialize-InlineObject' {
            # a simple test to create an object
            #$NewObject = Initialize-InlineObject -Name "TEST_VALUE" -Status "TEST_VALUE"
            #$NewObject | Should -BeOfType InlineObject
            #$NewObject.property | Should -Be 0
        }
    }
}
