#
# OpenAPI Petstore
# This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'InlineObject1' {
    Context 'InlineObject1' {
        It 'Initialize-InlineObject1' {
            # a simple test to create an object
            #$NewObject = Initialize-InlineObject1 -AdditionalMetadata "TEST_VALUE" -File "TEST_VALUE"
            #$NewObject | Should -BeOfType InlineObject1
            #$NewObject.property | Should -Be 0
        }
    }
}
